name: smart_greenhouse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  excel: ^4.0.6
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  open_file: ^3.5.10
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  share_plus: ^10.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
